# Generated by Django 3.0.7 on 2020-06-15 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='sched_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='sched_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user', 'service', 'sched_date')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sched',
        ),
    ]
